version: '3.8'

services:
  farway-website:
    build: .
    container_name: farway-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      # Dokploy labels for automatic configuration
      - "traefik.enable=true"
      - "traefik.http.routers.farway-website.rule=Host(`farway.quantumtaskai.com`)"
      - "traefik.http.routers.farway-website.tls=true"
      - "traefik.http.routers.farway-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.farway-website.loadbalancer.server.port=80"
      # Security headers middleware
      - "traefik.http.middlewares.farway-security.headers.frameDeny=true"
      - "traefik.http.middlewares.farway-security.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.farway-security.headers.browserXssFilter=true"
      - "traefik.http.middlewares.farway-security.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.routers.farway-website.middlewares=farway-security"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s